<a href="https://colab.research.google.com/github/RAFA-CK/python_basics/blob/main/pyhtonbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
Num = [1, 2, 3, 4, 5]
square = [i**2 for i in Num]
print(square)

for i in range(1,6):
  print(i)


[1, 4, 9, 16, 25]
1
2
3
4
5


What is the use of a function?

A function is used to organize your code into reusable, manageable pieces that perform specific tasks.

Instead of writing the same code again and again, you can put it inside a function and just call that function whenever you need it.

In [15]:
from re import A
def greet(name):
  print("hello " + name + "!")

greet("alice")

def add(a,b):
  print(a+b)
add(3,4)

def multiple(a,b,c):
  print(a*b*c)
multiple(2,3,4)


hello alice!
7
24


In [19]:

name={}
for i in range(2):
    s_name=input("give name:")
    mark=int(input("s_mark:"))
if mark >=90:
             give='A'
elif mark >=75:
             give='B'
elif mark >=50:
             give='C'
else:
    give="f"
name[s_name]=give
for s_name, give in name.items():
    print(f"{s_name}: {give}")


give name:rafa
s_mark:96
give name:meera
s_mark:45
meera: f


In [20]:
import numpy as np
f=np.array([1,2,3,4,5])
print(f)
c=(f+5)
print(c)
d=(f*5)
print(d)
s=(f**5)
print(s)
e=np.sum(f)
t=np.mean(f)
p=np.min(f)
d=np.max(f)
w=np.std(f)
print(e,t,p,d,w)
u=np.sort(f)
print(u)
f1=f>4
print(f1)


[1 2 3 4 5]
[ 6  7  8  9 10]
[ 5 10 15 20 25]
[   1   32  243 1024 3125]
15 3.0 1 5 1.4142135623730951
[1 2 3 4 5]
[False False False False  True]


🧩 What is a DataFrame?

A DataFrame (from the pandas library — usually imported as pd) is a table-like data structure used for storing and analyzing data in Python.

It’s very similar to an Excel spreadsheet or a SQL table — it has rows and columns.

In [26]:
import pandas as pd
data={
    "name":["rafa","anjana","anitta"],
    "mark":[46,46,46]
}
df= pd.DataFrame(data)
print(df)

     name  mark
0    rafa    46
1  anjana    46
2  anitta    46
